config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  devise_scope :user do
    authenticated :user do
      root :to => "foods#index", as: :authenticated_root
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    unauthenticated :user do
      root :to => "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :users, only: [:index]
  resources :foods, except: [:update]
  resources :public_recipes,except: [:update]
  resources :shopping_lists, except: [:update]

  resources :recipes do
    resources :recipe_foods, only: [:create, :destroy]
  end

  resources :inventories, except: [:update] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end 

  get 'shopping_lists/index'
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, foreign_key: :inventory_id, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true

  def calculate_foods(recipe)
    shopping_list = []
    recipe.recipe_foods.includes(:food).each do |recipe_food|
      food = recipe_food.food
      inventory_food = inventory_foods.where(food_id: food.id)[0]
      unless inventory_food
        shopping_list << [food.food, "#{recipe_food.quantity} #{food.measurement_unit}",
                          recipe_food.quantity * food.price]
        next
      end
      quantity_needed = recipe_food.quantity - inventory_food.quantity
      quantity_needed = 0 if quantity_needed.negative?
      if inventory_food && quantity_needed != 0
        shopping_list << [food.food, "#{quantity_needed} #{food.measurement_unit}", quantity_needed * food.price]
      end
    end
    shopping_list
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @inventories = Inventory.all
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = current_user.inventories.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventories_path, notice: 'Inventory created successfully.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    authorize! :destroy, @inventory
    @inventory.destroy!

    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory removed successfully.' }
    end
  end

  def show
    @inventory = Inventory.find(params[:id])
    @foods = @inventory.inventory_foods.includes(:food)
    @foody = Food.all
    @inventory_food = InventoryFood.new
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/index.html.erb
<section class="hero">
  <h1>Inventory List</h1>
  <%= link_to 'Add Inventory', new_inventory_path %>

  <% if @inventories.empty? %>
    <p>No inventories yet. Please add an inventory.</p>
  <% else %>

    <ul class="inventory">
      <% @inventories.each do |invt| %>
        <%= link_to inventory_path(invt.id) do %>
          <li class="public-recipe">
            <h3><%= invt.name %></h3>
            <p><%= invt.description %></p>
            <div>
              <% if can? :destroy, invt %>
                <%= link_to 'Remove', invt, data: { turbo_method: :delete, turbo_confirm: 'You are about to delete this inventory! Do you want to continue?' }, type:"button" %>
              <% else %>
                <%= link_to 'View', inventory_path(invt), type:"button" %>
              <% end %> 
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  <% end %>
</section>

app/views/inventories/new.html.erb
<section class="auth-forms">
  <div class="form-box">
    <div class="left-inventory"></div>
    <div class="right">
      <h2>Add New Inventory</h2>
      <%= form_with(model: @inventory) do |f| %>
        <div class="field">
          <%= f.text_field :name, placeholder: "Inventory Name", autofocus: true, required: true %>
        </div>
        <div class="field">
          <%= f.text_area :description, placeholder: "Type here the inventory description", required: true %>
        </div>
        <div class="actions">
          <%= f.submit "Add Inventory" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/inventories/show.html.erb
<section class="shopping">
  <div class="hero">
    <h2><%= @inventory.name %></h2>
    <% if can? :destroy, @inventory %>
      <a id="add-food-link">Add Food</a>
    <% end %>
  </div>
<div>
<% if @foods.empty? %>
<p>No food added to the inventory yet.
<%= @inventory.description %></p>
<% else %>
</div>
<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |fd| %>
      <tr>
        <td><%= fd.food.food %></td>
        <td><%= fd.quantity %></td>
        <td>
        <% if can? :destroy, fd %>
          <%= link_to 'Remove', inventory_inventory_food_path(:inventory_id => @inventory.id, :id => fd.id), 
          data: { turbo_method: :delete, turbo_confirm: 'You are about to delete this inventory food. Do you want to continue?' }, type:"button" %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<div class="inventory-modal" id="popup-modal">
    <div><span>x</span></div>
    <div>
      <h2>Add inventory food</h2>
      <hr>
    </div>

    <div>
      <%= form_with url: inventory_inventory_foods_path(@inventory.id), scope: :inventory_foods do |f| %>
        <div class="field">
          <%= f.select :food_id,@foody.collect { |food| [food.food, food.id] }, { :prompt => 'Choose food'}, required: true %>
        </div>

        <div class="field">
          <%= f.number_field :quantity, placeholder: "Quantity", required: true %>
        </div>

        <div class="actions">
          <%= f.submit "Add inventory food" %>
        </div>
      <% end %>
    </div>
</div>
</section>