config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  devise_scope :user do
    authenticated :user do
      root :to => "foods#index", as: :authenticated_root
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    unauthenticated :user do
      root :to => "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :users, only: [:index]
  resources :foods, except: [:update]
  resources :public_recipes,except: [:update]
  resources :shopping_lists, except: [:update]

  resources :recipes do
    resources :recipe_foods, only: [:create, :destroy]
  end

  resources :inventories, except: [:update] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end 

  get 'shopping_lists/index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: :recipe_id, dependent: :destroy

  validates :name, :preparation_time, :cooking_time, :description, presence: true

  def self.calculate_total_amount(recipe)
    total_amount = 0
    recipe.recipe_foods.includes(:food).each do |recipe_food|
      food = recipe_food.food
      total_amount += recipe_food.quantity * food.price
    end
    total_amount
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show destroy]

  def index
    @recipes = current_user.recipes
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_url, notice: 'Recipe Added successfully.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    authorize! :destroy, @recipe

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe removed successfully.' }
    end
  end

  def show
    @foods = current_user.foods
    @inventories = Inventory.all
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.public
      @recipe.update(public: false)
      flash.now[:notice] = 'Status changed to private.'
    else
      @recipe.update(public: true)
      flash.now[:notice] = 'Status changed to public'
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<section class="hero">
  <h1>Recipe List</h1>
  <%= link_to 'Add Recipe', new_recipe_path %>

  <% if @recipes.empty? %>
    <p>No recipes yet. Please add a recipe.</p>
  <% else %>
  <div> 
    <ul class="recipe-list">
      <% @recipes.each do |rcp| %>
        <%= link_to recipe_path(rcp.id) do %>
          <li>
            <div class="recipe-item">
              <h3><%= rcp.name %></h3>
              <% if can? :destroy, rcp %>
                <%= link_to 'Remove', rcp, data: { turbo_method: :delete, turbo_confirm: 'You are about to delete this recipe! Do you want to continue?' }, type:"button" %>
              <% end %>
            </div>
            <p><%= rcp.description %></p>
          </li>
        <% end %>
      <% end %> 
    </ul>
  </div>
  <% end %>
</section>

app/views/recipes/new.html.erb
<section class="auth-forms">
  <div class="form-box">
    <div class="left-recipe"></div>
    <div class="right">
      <h2>Create new recipe</h2>
      <%= form_with model: @recipe, method: :post, local: true do |f| %>
        <div class="field">
          <%= f.text_field :name, placeholder: "Recipe name", required: true %>
        </div>
        <div class="field">
          <%= f.text_field :cooking_time, placeholder: "Coooking time", required: true %>
        </div>
        <div class="field">
          <%= f.text_field :preparation_time, placeholder: "Preparation time", required: true %>
        </div>
        <div class="field">
          <%= f.text_area :description, placeholder: "Add description", required: true %>
        </div>
        <div class="actions">
          <%= f.submit "Add Recipe" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/recipes/show.html.erb
<section class="hero">
  <div>
    <h3><%= @recipe.name%></h3>
    <div>
      <div class="recipe-details">
        <div class="recipes">
          <div class="recipe-public">
            <p> Public: </p>
              <%= form_with url:recipe_path(@recipe.id), :method => :patch do |f| %>
                <%= f.check_box :public, checked: @recipe.public, onchange: "this.form.submit();" %>
              <% end %>
          </div>
          <p> Preparation time: <%= @recipe.preparation_time %> min</p>
        </div>
        <p> Cooking time: <%= @recipe.cooking_time %> min </p>
        <div class="recipe-buttons">
            <a id="openInventoryModal">Generate shopping list</a>
            <a id="openRecipeModal">Add ingredient</a>
        </div>
      </div>
    </div>
  </div>

  <% if @recipe.recipe_foods.empty? %>
    <p>No ingredients added yet.</p>
  <% else %>
  <table>
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe.recipe_foods.includes(:food).each do |recipe| %>
        <tr>
          <td><%= recipe.food.food %></td>
          <td><%= recipe.quantity %><%= recipe.food.measurement_unit %></td>
          <td>$<%= recipe.quantity * recipe.food.price %></td>
          <td>
            <% if can? :destroy, recipe %>
              <%= link_to 'Remove', recipe_recipe_food_path(@recipe.id, recipe.id), data: { turbo_method: :delete, turbo_confirm: 'You are about to remove this recipe food. Do you want to continue?' }, type:"button" %>
            <% end %>
          </td>
        </tr> 
      <% end %>
    </tbody>
  </table>
  <% end %>

  <div id="recipeModal" class="modal">
    <div>
      <span id='close-button'>x</span>  
    </div>
    <div>
      <h2>Add recipe food</h2>
      <hr>
    </div>

    <div>
      <%= form_with url: recipe_recipe_foods_path(params[:id]), scope: :recipe_foods do |f| %>
        <% if @foods.empty? %>
          <p>No food added! Please add food.</p>
        <% else %>
          <div class="field">
            <%= f.select :food_id,@foods.collect { |food| [food.food, food.id] }, { :prompt => 'Select food'}, required: true %>
          </div>
          <div class="field">
            <%= f.number_field :quantity, placeholder: "Quantity", required: true %>
          </div>
          <div class="actions">
            <%= f.submit "Add quantity" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div id="inventoryModal" class="modal">
    <div>
      <span id="close-button-inventory">x</span>
    </div>
    <div>
      <h2>Generating Shopping List</h2>
      <hr>
    </div>

    <p>Choose an inventory</p>

    <div>
      <%= form_with url: shopping_lists_path, method: :get  do |f| %>
        <div class="field">
          <%= f.select :inventory_id, @inventories.collect { |inventory| [inventory.name, inventory.id] }, :prompt => 'Select inventory', required: true %>
        </div>
        <div class="field">
          <%= f.hidden_field :recipe_id, value: @recipes.id, required: true %>
        </div>
        <div class="actions">
          <%= f.submit "Generate" %>
        </div>
      <% end %>
    </div>
  </div>
</section>